# Generated by Django 4.1.3 on 2022-12-07 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_blogs"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Blogs",
        ),
    ]
